import { db } from "./index";
import { customers, products, orders, orderItems, productDesigns, productSeries, bottleSizes } from "./schema";
import { BottleSizes, ProductSeries } from "@/constants/ProductConstants";

// Per-design price/MSRP/stock pulled from
// markdown files/database/Coldest_Designs_Spreadsheet.md's "Detailed Pricing"
// table (real per-variant data, incl. MSRP that legitimately varies by design
// within the same series+size — e.g. Limitless Ultra v8 36oz splits between
// $68.24 and $68.92 depending on design).
//
// Data-quality note (see Bug_Fixes.md Fix 10, "Still open"): the spreadsheet
// doesn't include actual unit counts, only an in-stock Yes/No flag, so
// quantity here is a placeholder (10 when in stock, 0 when not) rather than
// real inventory. Revisit if/when real stock counts are available.
type DesignSeed = {
  name: string;
  price: string;
  msrpPrice?: string;
  inStock: boolean;
  quantity: number;
};

// series/size are kept as plain strings here for readability; main() resolves
// them to product_series/bottle_sizes lookup ids at insert time.
type ProductSeed = Omit<typeof products.$inferInsert, "seriesId" | "sizeId"> & {
  series: string;
  size: string;
  designs: DesignSeed[];
};

const productSeeds = [
  {
    name: "Coldest Limitless Ultra v8 15oz",
    series: "Limitless Ultra v8",
    size: "15oz",
    material: "stainless_steel",
    hasHandle: true,
    leakProof: true,
    coldRetentionHours: 36,
    hotRetentionHours: 13,
    warranty: "lifetime",
    rating: "4.8",
    reviewCount: 842,
    designs: [
      { name: "Aura Farming Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Baby Birds Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Baby Dinosaur Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Baby Duckies Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Baby Puppy Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Berry Bae Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Blue Opal Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Bouquet of Sunflowers Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "But I'm Hungry Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Buzzer Beater Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Clover Floral Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Coldie Castle Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Crochet is Life Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Cuddly Puppy Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Farther Away Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Flirt & Flower Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Garden at Arles Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Glossy Pink Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Glowie Baby Fireflies Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Glowie Snowflakes Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Glowie Turtle Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Gold Dragon Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Green Dragon Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "I Need Icecream Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Irises Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "It's a Snowday Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Kissed Dream Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Love Pop Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Love of Music Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Magical Potions Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Mont Sainte Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Moonlight Mermaid Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Moonlight Seashells Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Mosaic Bloom Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Pink Bows Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Pink Petals Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Polished Steel Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Purple Moon Floral Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Pursuit of winning Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Red Luna Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Rocketship Alloy Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Secret Garden Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Soft Meadow Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Starry Night Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Starry Skulls Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Stealth Black Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Stung by a bee Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "Taste of Fall Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "The Big Bang Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "The European Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "The Great Wave Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "The Hamilton Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "The Marrakech Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "The Moroccan Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "The Ottoman Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "The Persian Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "The Reader Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "The World Stage Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Water Lilies Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
      { name: "Wizarding Skies Ultra", price: "44.99", msrpPrice: "53.99", inStock: false, quantity: 0 },
      { name: "XOXO Ultra", price: "44.99", msrpPrice: "53.99", inStock: true, quantity: 10 },
    ] satisfies DesignSeed[],
  },
  {
    name: "Coldest Limitless Ultra v8 24oz",
    series: "Limitless Ultra v8",
    size: "24oz",
    material: "stainless_steel",
    hasHandle: true,
    leakProof: true,
    coldRetentionHours: 36,
    hotRetentionHours: 13,
    warranty: "lifetime",
    rating: "4.8",
    reviewCount: 1575,
    designs: [
      { name: "Aura Farming Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Baby Birds Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Baby Dinosaur Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Baby Duckies Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Baby Puppy Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Berry Bae Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Bouquet of Sunflowers Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Buzzer Beater Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Candy Hearts Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Clover Floral Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Coldie Castle Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Crochet is Life Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Cuddly Puppy Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Farther Away Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Flirt & Flower Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Garden at Arles Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Glossy Pink Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Glowie Baby Fireflies Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Glowie Snowflakes Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Gold Dragon Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Green Dragon Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "I need Icecream Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Irises Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "It's a Snowday Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Kissed Dream Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Love Pop Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Love of Music Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Magical Potions Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Mont Sainte Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Moonlight Mermaid Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Moonlight Seashells Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Mosaic Bloom Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Pink Bows Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Pink Petals Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Polished Steel Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Purple Moon Floral Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Pursuit of winning Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Red Luna Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Rocketship Alloy Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Secret Garden Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Soft Meadow Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Starry Night Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Starry Skulls Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Stealth Black Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Stung by a bee Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Taste of Fall Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "The Big Bang Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "The European Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "The Great Wave Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "The Hamilton Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "The Marrakech Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "The Moroccan Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "The Ottoman Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "The Persian Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "The World Stage Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Water Lilies Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Wizarding Skies Ultra", price: "49.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "XOXO Ultra", price: "49.99", msrpPrice: undefined, inStock: true, quantity: 10 },
    ] satisfies DesignSeed[],
  },
  {
    name: "Coldest Limitless Ultra v8 36oz",
    series: "Limitless Ultra v8",
    size: "36oz",
    material: "stainless_steel",
    hasHandle: true,
    leakProof: true,
    coldRetentionHours: 36,
    hotRetentionHours: 13,
    warranty: "lifetime",
    rating: "4.8",
    reviewCount: 2770,
    designs: [
      { name: "Across The Universe Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Astroflora Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Aura Farming Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Baby Birds Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Baby Duckies Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Berry Bae Ultra", price: "54.99", msrpPrice: "68.24", inStock: true, quantity: 10 },
      { name: "Black Dress Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Black and White Checkers Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Blue Checkers Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Blue Willow Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Buzzer Beater Ultra", price: "54.99", msrpPrice: "68.92", inStock: true, quantity: 10 },
      { name: "Candy Hearts Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Clover Floral Ultra", price: "54.99", msrpPrice: "68.92", inStock: true, quantity: 10 },
      { name: "Coldie Dream Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Courting Couples Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Crochet is Life Ultra", price: "54.99", msrpPrice: "68.24", inStock: true, quantity: 10 },
      { name: "Cuddly Puppy Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Deer Moon Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Ember Glowie Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Fantasy Nova Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Flirt & Flower Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Garden at Arles Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Glossy Pink Ultra", price: "54.99", msrpPrice: "68.92", inStock: true, quantity: 10 },
      { name: "Glowie Baby Fireflies Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Glowie Dragon Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Glowie Snowflakes Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Glowie Spiral Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Gold Dragon Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Greatest Show Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Green Dragon Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "I need Icecream Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Imbued Nova Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Irises Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Karmic Popsicle Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Love Pop Ultra", price: "54.99", msrpPrice: "68.92", inStock: true, quantity: 10 },
      { name: "Love of Music Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Magical Potions Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Magnolia Bloom Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Mont Sainte Ultra", price: "54.99", msrpPrice: "68.92", inStock: true, quantity: 10 },
      { name: "Moonlight Mermaid Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Moonlight Seashells Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Mosaic Bloom Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Pink Bows Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Pink Reflection Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Polished Steel Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Purple Nova Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Purple Oasis Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Pursuit of winning Ultra", price: "54.99", msrpPrice: "68.24", inStock: true, quantity: 10 },
      { name: "Red Luna Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Rocketship Alloy Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Royal Blue Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Secret Garden Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Snuggle Red Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Soft Meadow Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "Stained Glass Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Starry Night Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Stealth Black Ultra", price: "54.99", msrpPrice: "68.92", inStock: true, quantity: 10 },
      { name: "Stung by a bee Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Summer Dress Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Taste of Fall Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "The American Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "The Big Bang Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "The Dragonfly Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "The Great Wave Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "The Hamilton Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "The Marrakech Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "The Moroccan Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "The Ottoman Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "The Persian Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "The World Stage Ultra", price: "54.99", msrpPrice: "68.24", inStock: true, quantity: 10 },
      { name: "Water Lilies Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Wine and Willow Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
      { name: "Wizarding Skies Ultra", price: "54.99", msrpPrice: "68.24", inStock: false, quantity: 0 },
      { name: "XOXO Ultra", price: "54.99", msrpPrice: "68.92", inStock: false, quantity: 0 },
    ] satisfies DesignSeed[],
  },
  {
    name: "Coldest Limitless Ultra v8 46oz",
    series: "Limitless Ultra v8",
    size: "46oz",
    material: "stainless_steel",
    hasHandle: true,
    leakProof: true,
    coldRetentionHours: 36,
    hotRetentionHours: 13,
    warranty: "lifetime",
    rating: "4.8",
    reviewCount: 4550,
    designs: [
      { name: "Across The Universe Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Astroflora Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Aura Farming Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Baby Birds Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Baby Duckies Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Berry Bae Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Black Dress Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Black and White Checkers Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Blue Checkers Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Blue Willow Ultra", price: "64.99", msrpPrice: "81.02", inStock: true, quantity: 10 },
      { name: "Buzzer Beater Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Clover Floral Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Coldie Dream Ultra", price: "64.99", msrpPrice: "81.02", inStock: false, quantity: 0 },
      { name: "Courting Couples Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Crochet is Life Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Cuddly Puppy Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Deer Moon Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Ember Glowie Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Fantasy Nova Ultra", price: "64.99", msrpPrice: "81.02", inStock: false, quantity: 0 },
      { name: "Flirt & Flower Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Garden at Arles Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Ghosts Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Glossy Pink Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Glowie Baby Fireflies Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Glowie Dragon Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Glowie Snowflakes Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Glowie Spiral Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Gold Mermaid Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Greatest Show Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Green Dragon Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "I need Icecream Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Imbued Nova Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Irises Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Karmic Popsicle Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Love Pop Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Love of Music Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Magical Potions Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Magnolia Bloom Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Molten Ivory Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Mont Sainte Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Moonlight Mermaid Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Moonlight Seashells Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Mosaic Bloom Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Pink Bows Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Pink Petals Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Pink Reflections Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Polished Steel Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Purple Nova Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Purple Oasis Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Pursuit of winning Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Red Luna Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Rocketship Alloy Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Royal Blue Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Secret Garden Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Snowstorm Floral Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Snuggle Red Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Soft Meadow Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Stained Glass Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Starry Night Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "Stealth Black Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Stung by a bee Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Summer Dress Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Taste of Fall Ultra", price: "64.99", msrpPrice: "81.02", inStock: true, quantity: 10 },
      { name: "The American Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "The Big Bang Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "The Dragonfly Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "The Great Wave Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "The Hamilton Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "The Marrakech Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "The Moroccan Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "The Ottoman Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "The Persian Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "The Reader Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "The World Stage Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Turtly Green Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Water Lilies Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Wine and Willow Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
      { name: "Wizarding Skies Ultra", price: "64.99", msrpPrice: "79.92", inStock: false, quantity: 0 },
      { name: "XOXO Ultra", price: "64.99", msrpPrice: "79.92", inStock: true, quantity: 10 },
    ] satisfies DesignSeed[],
  },
  {
    name: "Coldest Tumbler v2 20oz",
    series: "Tumbler v2",
    size: "20oz",
    material: "stainless_steel",
    hasHandle: false,
    leakProof: false,
    coldRetentionHours: 36,
    hotRetentionHours: 13,
    warranty: "lifetime",
    rating: "4.8",
    reviewCount: 930,
    designs: [
      { name: "Aura Farming Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Baby Birds Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Baby Dinosaur Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Baby Duckies Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Baby Paws Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Baby Puppy Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Berry Bae Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Blue Opal Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Bouquet of Sunflowers Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Buzzer Beater Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Candy Hearts Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Clover Floral Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Coldie Castle Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Crochet is Life Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Farther Away Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Flirt & Flower Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Garden at Arles Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Ghosts Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Glossy Pink Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Glowie Baby Fireflies Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Glowie Snowflakes Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Glowie Spiral Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Glowie Turtle Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Green Dragon Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Haunted Webs Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "I need Icecream Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Irises Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "It's a Snowday Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Love Pop Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Love of Music Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Magical Potions", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Magnolia Bloom Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Mont Sainte Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Moonlight Mermaid Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Moonlight Seashells Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Mosaic Bloom Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Mr. Snowie Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Pink Bows Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Pursuit of winning Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Red Dragon Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Red Luna Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Rocketship Alloy Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Secret Garden Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Snowstorm Floral Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Soft Meadow Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Starry Night Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Starry Skulls Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "Stealth Black Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Stung by a bee Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "The American Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "The Big Bang Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "The Dragonfly Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "The European Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "The Great Wave Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "The Hamilton Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "The Marrakech Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "The Morrocan Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "The Ottoman Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "The Persian Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "The Reader Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "The World Stage Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Water Lilies Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
      { name: "Wizarding Skies Ultra", price: "29.99", msrpPrice: "40.00", inStock: false, quantity: 0 },
      { name: "XOXO Ultra", price: "29.99", msrpPrice: "40.00", inStock: true, quantity: 10 },
    ] satisfies DesignSeed[],
  },
  {
    name: "Coldest Mini 6.7oz",
    series: "Mini",
    size: "6.7oz",
    material: "stainless_steel",
    hasHandle: false,
    leakProof: true,
    coldRetentionHours: 36,
    hotRetentionHours: 13,
    warranty: "lifetime",
    rating: "4.7",
    reviewCount: 1082,
    designs: [
      { name: "Baby Dinosaur Ultra", price: "29.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Baby Duckies Ultra", price: "29.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Berry Bae Ultra", price: "29.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Candy Hearts Ultra", price: "29.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Crochet is Life Ultra", price: "29.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Ghosts Ultra", price: "29.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Glossy Pink Ultra", price: "29.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Glowie Baby Fireflies", price: "29.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Glowie Butterflies Ultra", price: "29.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Glowie Snowflakes Ultra", price: "29.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Glowie Turtle Ultra", price: "29.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Green Dragon Ultra", price: "29.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Karmic Popsicle Ultra", price: "29.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Moonlight Seashells Ultra", price: "29.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Pink Bows Ultra", price: "29.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Pursuit of winning Ultra", price: "29.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Rocketship Alloy Ultra", price: "29.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Secret Garden Ultra", price: "29.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Snuggle Red Ultra", price: "29.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "Soft Meadow Ultra", price: "29.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "Stealth Black Ultra", price: "29.99", msrpPrice: undefined, inStock: true, quantity: 10 },
      { name: "The Big Bang", price: "29.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "The World Stage", price: "29.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "The World Stage Ultra", price: "29.99", msrpPrice: undefined, inStock: false, quantity: 0 },
      { name: "XOXO Ultra", price: "29.99", msrpPrice: undefined, inStock: true, quantity: 10 },
    ] satisfies DesignSeed[],
  },
  {
    name: "Coldest Limitless Gallon 128oz",
    series: "Limitless Gallon",
    size: "128oz",
    material: "stainless_steel",
    hasHandle: true,
    leakProof: true,
    coldRetentionHours: 100,
    hotRetentionHours: 13,
    warranty: "lifetime",
    rating: "4.8",
    reviewCount: 350,
    designs: [
      { name: "Berry Bae Ultra", price: "114.99", msrpPrice: "129.99", inStock: true, quantity: 10 },
      { name: "Blue Opal Ultra", price: "114.99", msrpPrice: "129.99", inStock: true, quantity: 10 },
      { name: "Buzzer Beater Ultra", price: "114.99", msrpPrice: "129.99", inStock: false, quantity: 0 },
      { name: "Candy Cane Ultra", price: "114.99", msrpPrice: "116.99", inStock: false, quantity: 0 },
      { name: "Cuddly Puppy Ultra", price: "114.99", msrpPrice: "89.99", inStock: true, quantity: 10 },
      { name: "Farther Away Ultra", price: "114.99", msrpPrice: "116.99", inStock: false, quantity: 0 },
      { name: "Ghosts Ultra", price: "114.99", msrpPrice: "116.99", inStock: true, quantity: 10 },
      { name: "Gold Dragon Ultra", price: "114.99", msrpPrice: "116.99", inStock: true, quantity: 10 },
      { name: "I need Icecream Ultra", price: "114.99", msrpPrice: "116.99", inStock: false, quantity: 0 },
      { name: "Love Pop Ultra", price: "114.99", msrpPrice: "129.99", inStock: false, quantity: 0 },
      { name: "Magical Potions Ultra", price: "114.99", msrpPrice: "129.99", inStock: true, quantity: 10 },
      { name: "Pink Petals Ultra", price: "114.99", msrpPrice: "116.99", inStock: true, quantity: 10 },
      { name: "Pursuit of winning Ultra", price: "114.99", msrpPrice: "129.99", inStock: true, quantity: 10 },
      { name: "Secret Garden Ultra", price: "114.99", msrpPrice: "129.99", inStock: false, quantity: 0 },
      { name: "Starry Night Ultra", price: "114.99", msrpPrice: "129.99", inStock: true, quantity: 10 },
      { name: "Stealth Black Ultra", price: "114.99", msrpPrice: "116.99", inStock: true, quantity: 10 },
      { name: "The American Ultra", price: "114.99", msrpPrice: "116.99", inStock: false, quantity: 0 },
      { name: "The Big Bang Ultra", price: "114.99", msrpPrice: "129.99", inStock: false, quantity: 0 },
      { name: "The European Ultra", price: "114.99", msrpPrice: "116.99", inStock: true, quantity: 10 },
      { name: "The Great Wave Ultra", price: "114.99", msrpPrice: "129.99", inStock: false, quantity: 0 },
      { name: "The Hamilton Ultra", price: "114.99", msrpPrice: "129.99", inStock: false, quantity: 0 },
      { name: "The Marrakech Ultra", price: "114.99", msrpPrice: "129.99", inStock: true, quantity: 10 },
      { name: "The Ottoman Ultra", price: "114.99", msrpPrice: "129.99", inStock: false, quantity: 0 },
      { name: "The World Stage Ultra", price: "114.99", msrpPrice: "129.99", inStock: true, quantity: 10 },
      { name: "Wizarding Skies Ultra", price: "114.99", msrpPrice: "116.99", inStock: false, quantity: 0 },
    ] satisfies DesignSeed[],
  },
  {
    name: "Coldest Universal 36oz",
    series: "Universal",
    size: "36oz",
    material: "stainless_steel",
    hasHandle: false,
    leakProof: true,
    coldRetentionHours: 36,
    hotRetentionHours: 13,
    warranty: "lifetime",
    rating: "4.8",
    reviewCount: 725,
    designs: [
      { name: "Irises v2", price: "45.99", msrpPrice: "49.99", inStock: true, quantity: 10 },
      { name: "Pink Reflections", price: "45.99", msrpPrice: "49.99", inStock: false, quantity: 0 },
      { name: "Stealth Black", price: "45.99", msrpPrice: "49.99", inStock: false, quantity: 0 },
      { name: "The Marrakech v2", price: "45.99", msrpPrice: "49.99", inStock: false, quantity: 0 },
    ] satisfies DesignSeed[],
  },
  {
    name: "Coldest First Responder 36oz",
    series: "First Responder",
    size: "36oz",
    material: "stainless_steel",
    hasHandle: true,
    leakProof: true,
    coldRetentionHours: 36,
    hotRetentionHours: 13,
    warranty: "lifetime",
    designs: [
      { name: "911 Dispatchers", price: "68.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Air Force", price: "68.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Army", price: "68.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Corrections", price: "68.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Firefighters", price: "68.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Marines", price: "68.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Navy", price: "68.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Nurses & Healthcare", price: "68.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Paramedic", price: "68.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Police", price: "68.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
    ] satisfies DesignSeed[],
  },
  {
    name: "Coldest First Responder 46oz",
    series: "First Responder",
    size: "46oz",
    material: "stainless_steel",
    hasHandle: true,
    leakProof: true,
    coldRetentionHours: 36,
    hotRetentionHours: 13,
    warranty: "lifetime",
    designs: [
      { name: "911 Dispatchers", price: "75.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Air Force", price: "75.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Army", price: "75.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Corrections", price: "75.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Firefighters", price: "75.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Marines", price: "75.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Navy", price: "75.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Nurses & Healthcare", price: "68.01", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Paramedic", price: "75.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
      { name: "Police", price: "75.00", msrpPrice: "75.00", inStock: true, quantity: 10 },
    ] satisfies DesignSeed[],
  },
] satisfies ProductSeed[];

const main = async () => {
  console.log("Seeding database...");

  await db.insert(productSeries).values(ProductSeries.map((s) => ({ name: s.id }))).onConflictDoNothing();
  await db.insert(bottleSizes).values(BottleSizes.map((s) => ({ code: s.id, description: s.description }))).onConflictDoNothing();

  const seriesIdByName = new Map(
    (await db.select().from(productSeries)).map((s) => [s.name, s.id])
  );
  const sizeIdByCode = new Map(
    (await db.select().from(bottleSizes)).map((s) => [s.code, s.id])
  );

  const insertedProducts = await db
    .insert(products)
    .values(
      productSeeds.map(({ designs, series, size, ...p }) => ({
        ...p,
        seriesId: seriesIdByName.get(series)!,
        sizeId: sizeIdByCode.get(size)!,
      }))
    )
    .returning({ id: products.id, seriesId: products.seriesId, sizeId: products.sizeId });

  const designRows = insertedProducts.flatMap((p) => {
    const seed = productSeeds.find(
      (s) => seriesIdByName.get(s.series) === p.seriesId && sizeIdByCode.get(s.size) === p.sizeId
    )!;
    return seed.designs.map((d) => ({ ...d, productId: p.id }));
  });
  await db.insert(productDesigns).values(designRows);

  // Seed customers
  const customerIds = await db.insert(customers).values([
    {
      firstName: "Sarah",
      lastName: "Johnson",
      email: "sarah.johnson@example.com",
      phone: "555-123-4567",
      address1: "123 Fitness Ave",
      city: "Austin",
      state: "TX",
      zipCode: "78701",
      notes: "Prefers eco-friendly products",
    },
    {
      firstName: "Mike",
      lastName: "Chen",
      email: "mike.chen@example.com",
      phone: "555-987-6543",
      address1: "456 Wellness St",
      city: "San Francisco",
      state: "CA",
      zipCode: "94105",
      notes: "Corporate bulk orders",
    },
  ]).returning({ id: customers.id });

  // Seed orders
  const orderIds = await db.insert(orders).values([
    {
      customerId: customerIds[0].id,
      customDesignText: "Sarah's Hydration",
      designNotes: "Logo on both sides",
      status: "design",
      totalPrice: "49.98",
      assignedTo: "designer@example.com",
    },
    {
      customerId: customerIds[1].id,
      customDesignText: "Chen Corp",
      designNotes: "Company logo in blue",
      status: "production",
      totalPrice: "999.50",
      assignedTo: "production@example.com",
    },
  ]).returning({ id: orders.id });

  await db.insert(orderItems).values([
    {
      orderId: orderIds[0].id,
      productId: insertedProducts[0].id,
      quantity: 2,
      selectedColor: "Stealth Black Ultra",
      unitPrice: "44.99",
      discount: "0",
    },
    {
      orderId: orderIds[1].id,
      productId: insertedProducts[1].id,
      quantity: 50,
      selectedColor: "Berry Bae Ultra",
      unitPrice: "49.99",
      discount: "0",
    },
  ]);

  console.log("Seeding completed");
};

main().catch((error) => {
  console.error("Error during seeding:", error);
  process.exit(1);
});
